spring.application.name=encher

spring.datasource.url=jdbc:mysql://localhost:3306/encherdb
spring.datasource.username=user
spring.datasource.password=user
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
stripe.apiKey=sk_test_51SZF9gRGlF6gfv1Z15NLNlUnwIZ0KXPFSMdgI3ydEueyXK2l3tVWrlhX5PR703pXGzla6lge2Zqf0V44myw2AHdN00VY9oLkno
stripe.currency=eur